## numpy random choice

- [docs](https://het.as.utexas.edu/HET/Software/Numpy/reference/generated/numpy.random.choice.html)

- [datascienceschool](https://datascienceschool.net/view-notebook/8bf41f87a08b4c44b307799577736a28/)

데이터 샘플링

이미 있는 데이터 집합에서 일부를 무작위로 선택하는 것을 샘플링(sampling)이라고 한다. 

샘플링에는 choice 명령을 사용한다. choice 명령은 다음과 같은 인수를 가질 수 있다.

numpy.random.choice(a, size=None, replace=True, p=None)

a : 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로 데이터 생성

size : 정수. 샘플 숫자

replace : 불리언. True이면 한번 선택한 데이터를 다시 선택 가능

p : 배열. 각 데이터가 선택될 수 있는 확률

### basic

In [4]:
import numpy as np

In [5]:
# Generate a uniform random sample from np.arange(5) of size 3:

np.random.choice(5, 3)

array([0, 4, 3])

In [6]:
# Generate a non-uniform random sample from np.arange(5) of size 3:

np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 0, 0])

In [7]:
# Generate a uniform random sample from np.arange(5) of size 3 without replacement:

np.random.choice(5, 3, replace=False)

array([0, 3, 1])

In [8]:
# Generate a non-uniform random sample from np.arange(5) of size 3 without replacement:

np.random.choice(5, 3, replace=False, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 0, 2])

In [9]:
# Any of the above can be repeated with an arbitrary array-like instead of just integers. For instance:

aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['pooh', 'pooh', 'Christopher', 'pooh', 'piglet'], dtype='<U11')