numpy argsort
--------

```python
numpy.argsort(a, axis=-1, kind=None, order=None)
```

Returns the indices that would sort an array.
> Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.

array의 정렬된 indices를 돌려줍니다.


## Example - One dimensional array

In [2]:
import numpy as np

In [3]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

3은 index number가 0 이니까 정렬을 할 때 가장 뒤로 보내야 한다. -> 그래서 array([1, 2, 0]) 모양이 나옴

In [4]:
x[np.argsort(x)]

array([1, 2, 3])

-----

In [6]:
x = np.array([3, 1, 2, 6, 5])
np.argsort(x)

array([1, 2, 0, 4, 3])

In [7]:
x[np.argsort(x)]

array([1, 2, 3, 5, 6])

## Example - Two-dimensional array

In [22]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [17]:
ind = np.argsort(x, axis=0)  # sorts along first axis (down) - axis=0 방향으로 순서 정렬
ind

array([[0, 1],
       [1, 0]])

In [11]:
# Apply index_array from argsort to an array as if by calling sort.

np.take_along_axis(x, ind, axis=0)  # same as np.sort(x, axis=0)

array([[0, 2],
       [2, 3]])

In [30]:
# https://stackoverflow.com/questions/33140674/argsort-for-a-multidimensional-ndarray

def foo(a):
    i = np.argsort(a, axis=1)
    return (np.arange(a.shape[0])[:,None], i)

In [31]:
y = np.array([[7, 3], [5, 1]])

In [32]:
y[foo(y)]

array([[3, 7],
       [1, 5]])

In [36]:
ind = np.argsort(y, axis=1)  # sorts along last axis (across)
ind

array([[1, 0],
       [1, 0]])

In [42]:
def boo(a):
    i = np.argsort(a, axis=0)
    return (np.arange(a.shape[0])[None,:], i)

In [43]:
y[boo(y)]

array([[3, 1],
       [7, 5]])

In [15]:
ind = np.argsort(x, axis=1)  # sorts along last axis (across)
ind

array([[0, 1],
       [0, 1]])

In [16]:
np.take_along_axis(x, ind, axis=1)  # same as np.sort(x, axis=1)

array([[0, 3],
       [2, 2]])

## Example - Indices of the sorted elements of a N-dimensional array

In [33]:
ind = np.unravel_index(np.argsort(x, axis=None), x.shape)
ind

(array([0, 1, 1, 0]), array([0, 0, 1, 1]))

In [34]:
x[ind]

array([0, 2, 2, 3])

In [35]:
# Sorting with keys:

x = np.array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])
x

array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])