In [1]:
import numpy as np

### Quiz 1

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

In [7]:
A = np.vstack([v1, v2, v3])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
B = np.column_stack([v1, v2, v3])
B

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
C = np.array(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ]
)

In [11]:
C

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
D = np.column_stack([C, v3])

In [13]:
D

array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [14]:
E = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
)

In [15]:
E

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# 1행 4열 성분
E[0, 3]

4

In [18]:
# E의 1~2행의 3열에 해당하는 부분행렬
E[0:2, 2]

array([3, 7])

In [19]:
E[0, 0] = -1
E

array([[-1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

-----------

In [20]:
A = np.array([[1., 2.], [3., 4.]])
B = np.array([[2., 2.], [1., 3.]])
C = np.array([[4., 5., 6.], [7., 8., 9.]])
v = np.array([[10.], [20.]])

In [21]:
A + B

array([[3., 4.],
       [4., 7.]])

In [22]:
np.matmul(A, B)

array([[ 4.,  8.],
       [10., 18.]])

In [23]:
# 행렬의 거듭제곱

np.linalg.matrix_power(A, 2)

array([[ 7., 10.],
       [15., 22.]])

In [24]:
# 행렬의 거듭제곱

np.linalg.matrix_power(A, 3)

array([[ 37.,  54.],
       [ 81., 118.]])

In [25]:
# 행렬의 성분별 거듭제곱 A**2

A**2

array([[ 1.,  4.],
       [ 9., 16.]])

In [27]:
# 대각행렬

M = np.diag([1, 2, 3])
M

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [28]:
# 블록행렬 생성

D11 = np.array([[1., 2.], [3., 4.]])
D12 = np.array([[5], [6]])
D21 = np.array([[7, 7]])
D22 = np.array([[8]])

D = np.block([[D11, D12], [D21, D22]])
D

array([[1., 2., 5.],
       [3., 4., 6.],
       [7., 7., 8.]])